name: CI

on: [push]

# GitHub Actions don't support cache yet so need...
# to install first and run steps after. This causes
# steps to run sequentially instead of parallel tho.

jobs:
  lint-test-build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: nuxt/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: nuxt/actions-yarn@master
        with:
          args: lint
      - name: Test
        uses: nuxt/actions-yarn@master
        with:
          args: test
      - name: Build
        uses: nuxt/actions-yarn@master
        with:
          args: build
  test-examples:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: nuxt/actions-yarn@master
        with:
          args: install
      - name: Build Examples
        uses: nuxt/actions-yarn@master
        with:
          args: build:examples
      - name: Test Examples
        with:
          args: yarn test:examples
        env:
          GIMBAL_MYSQL_HOST: ${{ secrets.GIMBAL_MYSQL_HOST }}
          GIMBAL_MYSQL_PASSWORD: ${{ secrets.GIMBAL_MYSQL_PASSWORD }}
          GIMBAL_MYSQL_USERNAME: ${{ secrets.GIMBAL_MYSQL_USERNAME }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
