name: CI

on: [push]

# GitHub Actions don't support cache yet so need...
# to install on each step.

jobs:
  lint-test-build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: nuxt/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: nuxt/actions-yarn@master
        with:
          args: lint
      - name: Test
        uses: nuxt/actions-yarn@master
        with:
          args: test
      - name: Build
        uses: nuxt/actions-yarn@master
        with:
          args: build
      - name: Build Examples
        uses: nuxt/actions-yarn@master
        with:
          args: build:examples
      - name: Test Examples
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn test:examples
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
