name: Lint & Test

on: [push]

# GitHub Actions don't support cache yet so need
# to install on each step.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printenv
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: nuxt/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: nuxt/actions-yarn@master
        with:
          args: lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: nuxt/actions-yarn@master
        with:
          args: install
      - name: Test
        uses: nuxt/actions-yarn@master
        with:
          args: test
